#
#
#
version: "3.1"
services:
  memcached:
    image: memcached:alpine
    container_name: ${APP_CODE}-memcached
  redis:
    image: redis:alpine
    container_name: ${APP_CODE}-redis
#  elasticsearch:
#    image: elasticsearch:6.5.4
#    container_name: gesfin-elasticsearch
  nginx:
    image: nginx:alpine
    container_name: ${APP_CODE}-nginx
    working_dir: /var/www
    volumes:
      - ${APP_DIR}:/var/www
      - ${APP_DIR}/storage/logs:/var/log
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT}:80"
  php:
    build: .
    container_name: ${APP_CODE}-php
    working_dir: /var/www
    volumes:
      - ${APP_DIR}:/var/www
      - ${APP_DIR}/storage/logs:/var/log
      - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

