#
#
#
version: "3.1"
services:
#  memcached:
#    image: memcached:alpine
#    container_name: ea-memcached
#
#  redis:
#    image: redis:alpine
#    container_name: ea-redis
#
#  elasticsearch:
#    image: elasticsearch:6.5.4
#    container_name: ea-elasticsearch
#
  nginx:
    image: nginx:alpine
    container_name: gesfin-nginx
    working_dir: /var/www
    volumes:
      - ${APP_DIR}:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT}:80"
  php:
    build: .
    container_name: gesfin-php
    working_dir: /var/www
    volumes:
      - ${APP_DIR}:/var/www
      - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

